# Spring
spring:
  application:
    name: mi-extraction-service

info:
  app:
    name: ${spring.application.name}

# Application Insights
application-insights:
  default:
    modules:
      WebSyntheticRequestTelemetryInitializer:
        enabled: false

# Azure
azure:
  application-insights:
    instrumentation-key: ""
  managed-identity:
    client-id: "clientId"
  storage-account:
    staging:
      name: "staging"
      connection-string: "connString"
    export:
      name: "export"
      connection-string: "connString"

# Export
export:
  ccd:
    enabled: true
    date-field: ce_created_date
  notify:
    enabled: true
    date-field: created_at
    timezone: Europe/London # Dates are stored in UTC but processed by Notify in BST
  payment-history:
    enabled: true
    date-field: sh_date_updated
  payment-allocation:
    enabled: true
    date-field: date_created
  payment-remission:
    enabled: true
    date-field: date_updated
  payment-fee:
    enabled: true
    date-field: date_updated

# Whitelist
container-whitelist: ${T(java.util.Collections).emptyList()}

# Dates
retrieve-from-date: 1970-01-01
retrieve-to-date: 1970-01-02

# Archiving
archive:
  compression:
    enabled: true
  encryption:
    enabled: false
    password:

# Mail
mail:
  targets: "TestMailAddress"
  gov-uk:
    api-key: "testApiKey"
    templates:
      blob-url: "testTemplate"

# Smoke Test
smoke:
  test:
    enabled: false
