# Java
# Package your Java project.
# Add steps that install, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: '$(SourceBranchName)-$(Build.SourceVersion) Build-$(Build.BuildId)'

trigger:
  batch: true
  branches:
    include:
      - master

  tags:
    include:
      - v*

pr:
  autoCancel: true
  branches:
    include:
      - master

variables:
  #  group: pipeline-env-variables
  ${{ if eq( variables['Build.Reason'], 'PullRequest') }}:
    environment: 'test'
    env.upper: 'TEST'
  ${{ if ne( variables['Build.Reason'], 'PullRequest') }}:
    environment: 'test' #Uset test and promoting to stg until prod is ready
    env.upper: 'TEST'
  env.prom: 'stg'
  env.prom.upper: 'STG'
  application.name: 'mi-extraction-service'
  azure.container.registry: 'ssprivate$(env).azurecr.io'
  azure.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.upper)'
  azure.aks.resourcegroup: 'ss_$(env)_kubernetes_resource_group'
  azure.aks.cluster: 'ss_aks_$(env)'
  azure.prom.subscription.endpoint: 'DTS-SHAREDSERVICES-$(env.prom.upper)'
  azure.prom.aks.resourcegroup: 'ss_$(env.prom)_kubernetes_resource_group'
  azure.prom.aks.cluster: 'ss_aks_$(env.prom)'
  manual.branch.prefix: 'master'
  product: 'mi'
  vault: 'mi-vault-$(env)'
  azure.prom.acr: 'ssprivate$(env.prom)'

resources:
  repositories:
    - repository: mi-core
      type: github
      name: hmcts/mi-core-lib
      endpoint: hmcts

stages:
  - template: pipeline-steps/templates/build-deploy-stage.yaml@mi-core
    parameters:
      env: $(environment)
      applicationName: $(application.name)
      product: $(product)
      chartEnv: $(environment)
      preIntegrationTest: true
      functionalTest: true
      azureVault: $(vault)
      azureSecreKeys: 'mail-username,mail-password,archive-password'
      azureKeyMapping:
        - key: MAIL_USERNAME
          value: 'mail-username'
        - key: MAIL_PASSWORD
          value: 'mail-password'
        - key: ARCHIVE_PASSWORD
          value: 'archive-password'
        - key: AZURE_CONTAINER_REGISTRY
          value: $(azure.container.registry)
