mi-job:
  image: ${IMAGE_NAME}
  keyVaultsUsepodidentity: false
  environment:
    APPINSIGHTS_INSTRUMENTATIONKEY: 5be27762-da20-4aaf-bc55-6b95a0c6ef6d
    CONTAINER_WHITELIST: ^exp-testcontainer-${BUILD_VERSION}.*
    EXPORT_SOURCES_EXP_ENABLED: true
    EXPORT_SOURCES_EXP_PREFIX: ${BUILD_VERSION}
    EXPORT_SOURCES_EXP_DATEFIELD: date_updated
    EXPORT_SOURCES_EXP_TYPE: prefix
    MI_CLIENT_ID: 3b98a9ff-c77c-42bf-a539-0c7f8316e22d
    RETRIEVE_FROM_DATE: 1970-01-01
    RETRIEVE_TO_DATE: 1970-01-02
global:
  subscriptionId: "74dacd4f-a248-45bb-a2f0-af700dc4cf68"
  environment: stg
